version: '3.7'

x-container-common: &container-common
  restart: ${CONTAINER_RESTART-on-failure}
  networks:
    - hashicorp

services:
  hashicorp:
    <<: *container-common
    image: consensys/quorum-hashicorp-vault-plugin:v1.1.3
    tty: true
    cap_add:
      - IPC_LOCK
    volumes:
      - hashicorp-plugin:/vault/plugins
      - ./config/config.hcl:/vault/config.hcl:ro
      - ./scripts/agent-init.sh:/usr/local/bin/kvv2-init.sh
    environment:
      VAULT_ADDR: http://hashicorp:8200
      VAULT_IS_READY: /vault/token/.ready
      ROOT_TOKEN_PATH: /vault/token/.root
    entrypoint:
      - sh
      - -c
      - |
        ( sleep 2 && vault-init.sh && kvv2-init.sh && cat > $${VAULT_IS_READY} ) &
         vault server -config=/vault/config.hcl
    ports:
      - 8200:8200

  hashicorp-agent:
    <<: *container-common
    image: consensys/quorum-hashicorp-vault-plugin:v1.1.3
    tty: true
    depends_on:
      - hashicorp
    cap_add:
      - IPC_LOCK
    environment:
      ROOT_TOKEN_PATH: /vault/token/.root
      VAULT_ADDR: http://vault:8200
      SECRET_FILE_PATH: /vault/token/secret
      ROLE_FILE_PATH: /vault/token/role
      VAULT_IS_READY: /vault/token/.ready
    volumes:
      - hashicorp-token:/vault/token
      - ./config/agent-config.hcl:/vault/config.hcl:ro
      - ./scripts/agent-init.sh:/usr/local/bin/agent-init.sh
    entrypoint:
      - sh
      - -c
      - |

        until [ -f ${VAULT_IS_READY} ]; do
          echo "[AGENT] waiting for vault to be ready..."
          sleep 1
        done

        agent-init.sh
        vault agent -config=/vault/config.hcl

  hashicorp-tls:
    <<: *container-common
    image: consensys/quorum-hashicorp-vault-plugin:v1.1.3
    container_name: hashicorp
    tty: true
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: https://hashicorp:8200
      VAULT_IS_READY: /vault/token/.ready
      ROOT_TOKEN_PATH: /vault/token/.root
      VAULT_CACERT: ${VAULT_CACERT-/vault/tls/ca.crt}
      VAULT_CLIENT_CERT: ${VAULT_CLIENT_CERT-/vault/tls/client.crt}
      VAULT_CLIENT_KEY: ${VAULT_CLIENT_KEY-/vault/tls/client.key}
    volumes:
      - hashicorp-plugin:/vault/plugins
      - ./tls:/vault/tls:ro
      - ./config/config-tls.hcl:/vault/config.hcl:ro
      - ./tls/ca.crt:/etc/ssl/certs/vault.crt
    entrypoint:
      - sh
      - -c
      - |
        ( sleep 2 && vault-init.sh && kvv2-init.sh && cat > $${VAULT_IS_READY} ) &
         vault server -config=/vault/config.hcl
    ports:
      - 8200:8200

  hashicorp-agent-tls:
    <<: *container-common
    image: consensys/quorum-hashicorp-vault-plugin:v1.1.3
    tty: true
    container_name: hashicorp-agent
    depends_on:
      - hashicorp-tls
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: ${VAULT_ADDR-https://hashicorp:8202}
      VAULT_CACERT: ${VAULT_CACERT-/vault/tls/ca.crt}
      VAULT_CLIENT_CERT: ${VAULT_CLIENT_CERT-/vault/tls/client.crt}
      VAULT_CLIENT_KEY: ${VAULT_CLIENT_KEY-/vault/tls/client.key}
    volumes:
      - hashicorp-token:/vault/token
      - ./config/agent-config-tls.hcl:/vault/config.hcl:ro
      - ./tls:/vault/tls:ro
    entrypoint: vault agent -config=/vault/config.hcl


volumes:
  hashicorp-token:
    driver: local
    name: hashicorp-token
  hashicorp-plugin:
    driver: local

networks:
  hashicorp:
    external:
      name: hashicorp
