version: '3.7'

x-container-common: &container-common
  restart: ${CONTAINER_RESTART-on-failure}
  networks:
    - hashicorp

services:
  hashicorp:
    <<: *container-common
    image: library/vault:1.8.2
    tty: true
    cap_add:
      - IPC_LOCK
    volumes:
      - hashicorp-plugin:/vault/plugins
      - ./tls:/vault/tls:ro
      - ./config/config.hcl:/vault/config.hcl:ro
    entrypoint: vault server -config=/vault/config.hcl
    ports:
      - 8200:8200

  hashicorp-init-tls:
    <<: *container-common
    build: .
    environment:
      VAULT_ADDR: ${VAULT_ADDR-https://hashicorp:8202}
      VAULT_CACERT: ${VAULT_CACERT-/vault/tls/ca.crt}
      VAULT_CLIENT_CERT: ${VAULT_CLIENT_CERT-/vault/tls/client.crt}
      VAULT_CLIENT_KEY: ${VAULT_CLIENT_KEY-/vault/tls/client.key}
      PLUGIN_PATH: ${PLUGIN_PATH-/vault/plugins}
      TOKEN_PATH: ${TOKEN_PATH-/vault/token}
      PLUGIN_VERSION: ${PLUGIN_VERSION-v1.0.0}
    restart: "no"
    depends_on:
      - hashicorp
    volumes:
      - hashicorp-token:/vault/token
      - hashicorp-plugin:/vault/plugins
      - ./scripts/init-tls.sh:/init.sh
      - ./scripts/plugin.sh:/plugin.sh
      - ./tls/ca.crt:/vault/tls/ca.crt:ro
      - ./tls/client.crt:/vault/tls/client.crt:ro
      - ./tls/client.key:/vault/tls/client.key:ro
    command: >
      sh -c "./plugin.sh && ./init.sh"

  hashicorp-init:
    <<: *container-common
    build: .
    environment:
      VAULT_ADDR: ${VAULT_ADDR-http://hashicorp:8200}
      PLUGIN_PATH: ${PLUGIN_PATH-/vault/plugins}
      TOKEN_PATH: ${TOKEN_PATH-/vault/token}
      PLUGIN_VERSION: ${PLUGIN_VERSION-v1.0.0}
    restart: "no"
    depends_on:
      - hashicorp
    volumes:
      - hashicorp-token:/vault/token
      - hashicorp-plugin:/vault/plugins
      - ./scripts/init.sh:/init.sh
      - ./scripts/plugin.sh:/plugin.sh
    command: >
      sh -c "./plugin.sh && ./init.sh"

  hashicorp-agent-tls:
    <<: *container-common
    environment:
      VAULT_ADDR: ${VAULT_ADDR-https://hashicorp:8202}
      VAULT_CACERT: ${VAULT_CACERT-/vault/tls/ca.crt}
    image: library/vault:1.8.2
    tty: true
    depends_on:
      - hashicorp
      - hashicorp-init-tls
    cap_add:
      - IPC_LOCK
    volumes:
      - hashicorp-token:/vault/token
      - ./config/agent-config-tls.hcl:/vault/config.hcl:ro
      - ./tls:/vault/tls:ro
    entrypoint: vault agent -config=/vault/config.hcl

  hashicorp-agent:
    <<: *container-common
    environment:
      VAULT_ADDR: ${VAULT_ADDR-http://hashicorp:8200}
    image: library/vault:1.8.2
    tty: true
    depends_on:
      - hashicorp
      - hashicorp-init
    cap_add:
      - IPC_LOCK
    volumes:
      - hashicorp-token:/vault/token
      - ./config/agent-config.hcl:/vault/config.hcl:ro
    entrypoint: vault agent -config=/vault/config.hcl

volumes:
  hashicorp-token:
    driver: local
    name: hashicorp-token
  hashicorp-plugin:
    driver: local

networks:
  hashicorp:
    external:
      name: hashicorp
