linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 5
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  depguard:
    list-type: blacklist
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc

linters:
  enable:
    - goconst
    - goimports
    - gocritic
    - golint
    - interfacer
    - maligned
    - misspell
    - stylecheck
    - unconvert
    - unparam

issues:
  max-same-issues: 10

run:
  deadline: 20m
  skip-dirs:
    - .gocache
    - build
    - mock
    - deps
    - vendor
    - tests
