codecov:
  require_ci_to_pass: false

coverage:
  range: 40..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 80%
        # Allow decreasing 2% of total coverage to avoid noise.
        threshold: 2%
        if_ci_failed: error
        informational: true
        flags:
          - "unittests"
          - "acceptance"
        branches:
          - main
        paths:
          - "src"
          - "pkg"
          - "cmd"
          - "!*/mock"
          - "!*/mocks"
          - "!*/testutils"
          - "!*/testdata"
          - "!tests/*"
          - "!src/infra/*"
    patch:
      default:
        target: 90%
        threshold: 0%
        informational: true
        flags:
          - "unittests"
          - "acceptance"
        paths:
          - "src"
          - "pkg"
          - "cmd"
          - "!*/mock"
          - "!*/mocks"
          - "!*/testutils"
          - "!*/testdata"
          - "!tests/*"
          - "!src/infra/*"

# https://docs.codecov.io/docs/codecovyml-reference#section-parsers
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
      
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no
  
ignore:
  - tests/*
  - main.go
  - src/infra/*
  - "*/testutils"
  - "*/testdata"
  - "*/mock"
  - "*/mocks"
