version: "3.7"

x-default-variables: &default-variables
  LOG_LEVEL: ${LOG_LEVEL-INFO}
  HTTP_HOST: ${HTTP_HOST-0.0.0.0}
  HTTP_PORT: ${HTTP_PORT-8080}
  NODE_ADDR: ${NODE_ADDR-http://validator2:8545}
  MANIFEST_PATH: ${MANIFEST_PATH-}

x-container-common: &container-common
  image: golang:1.15-buster
  restart: ${CONTAINER_RESTART-on-failure}
  entrypoint: /bin/main
  tty: true
  networks:
    - quorum
    - besu
    - hashicorp
  volumes:
    - ./build/bin/key-manager:/bin/main:ro

services:
  key-manager:
    <<: *container-common
    environment:
      <<: *default-variables
    ports:
      - 8080:8080
    restart: "no"
    command: run

networks:
  quorum:
    external:
      name: quorum
  besu:
    external:
      name: besu
  hashicorp:
    external:
      name: hashicorp

