version: "3.7"

x-default-variables: &default-variables
  LOG_LEVEL: ${LOG_LEVEL-INFO}
  HTTP_HOST: ${HTTP_HOST-localhost}
  HTTP_PORT: ${HTTP_PORT-8080}

x-container-common: &container-common
  image: golang:1.15-buster
  restart: ${CONTAINER_RESTART-on-failure}
  entrypoint: /bin/main
  tty: true
  networks:
    - key-manager
  volumes:
    - ./build/bin/key-manager:/bin/main:ro

services:
  key-manager:
    <<: *container-common
    environment:
      <<: *default-variables
    ports:
      - 8080:8080
    restart: "no"
    command: run

networks:
  key-manager:
    external:
      name: key-manager
