version: "3.7"

x-default-variables: &default-variables
  LOG_LEVEL: ${LOG_LEVEL-INFO}
  HTTP_HOST: ${HTTP_HOST-0.0.0.0}
  HTTP_PORT: ${HTTP_PORT-8080}
  MANIFEST_PATH: ${MANIFEST_PATH-/manifests}
  TEST_DATA: ${TEST_DATA-}

x-container-common: &container-common
  image: golang:1.15-buster
  restart: ${CONTAINER_RESTART-on-failure}
  entrypoint: /bin/main
  tty: true
  networks:
    - quorum
    - besu
    - hashicorp

services:
  key-manager:
    <<: *container-common
    environment:
      <<: *default-variables
    ports:
      - 8080:8080
    restart: "no"
    command: run
    volumes:
      - ./build/bin/key-manager:/bin/main:ro
      - ./deps/config:/manifests:ro
      - hashicorp-token:/vault/token:ro

networks:
  quorum:
    external:
      name: quorum
  besu:
    external:
      name: besu
  hashicorp:
    external:
      name: hashicorp

volumes:
  hashicorp-token:
    external:
      name: hashicorp-token

