package entities

type Account struct {
	// Address
	Address string

	// Attr
	Attr *Attributes

	// Metadata generated by the store
	Metadata *Metadata
}

func KeyToAccount(key *Key) *Account {
	// TODO: to be implemented
	return nil
}

func KeysToAccounts(key []*Key) []*Account {
	// TODO: to be implemented
	return nil
}
