version: '3.7'

x-container-common: &container-common
  restart: ${CONTAINER_RESTART-on-failure}
  networks:
    - qkm

x-postgres-common: &postgres-common
  environment:
    POSTGRES_PASSWORD: postgres

services:
  postgres-ssl:
    <<: *container-common
    <<: *postgres-common
    image: postgres:13.3-alpine
    # command: ["postgres", "-c", "max_connections=100"]
    # command: ["postgres", "-c", "log_statement=all"]
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
      -c ssl_ca_file=/var/lib/postgresql/ca.crt
    volumes:
      - db-data-api:/var/lib/postgresql/data
      - ./postgres/tls/tls.crt:/var/lib/postgresql/server.crt:ro
      - ./postgres/tls/tls.key:/var/lib/postgresql/server.key:ro
      - ./postgres/tls/ca.crt:/var/lib/postgresql/ca.crt:ro
    ports:
      - 5432

  postgres:
    <<: *container-common
    <<: *postgres-common
    image: postgres:13.4-alpine
    # command: ["postgres", "-c", "max_connections=100"]
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - db-data-api:/var/lib/postgresql/data
    ports:
      - 5432

volumes:
  db-data-api:
    driver: local

networks:
  qkm:
    driver: bridge
