version: '3.7'

x-container-common: &container-common
  restart: ${CONTAINER_RESTART-on-failure}
  networks:
    - postgres

x-postgres-common: &postgres-common
  environment:
    # update ./pgadmin/password as well when changing here
    POSTGRES_PASSWORD: postgres

services:
  postgres:
    <<: *container-common
    <<: *postgres-common
    image: postgres:13.3-alpine
    #    command: ["postgres", "-c", "max_connections=100"]
    #    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - db-data-api:/var/lib/postgresql/data
    ports:
      - 5432

  pgadmin:
    <<: *container-common
    image: dpage/pgadmin4:4.27
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    restart: unless-stopped
    volumes:
      - state-pgadmin:/root/.pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/password:/pgadmin4/password
    ports:
      - 9001:80

volumes:
  db-data-api:
    driver: local
  state-pgadmin:
    driver: local

networks:
  postgres:
    external:
      name: postgres
