// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	manifest "github.com/ConsenSysQuorum/quorum-key-manager/src/core/manifest"
	accounts "github.com/ConsenSysQuorum/quorum-key-manager/src/store/accounts"
	entities "github.com/ConsenSysQuorum/quorum-key-manager/src/store/entities"
	keys "github.com/ConsenSysQuorum/quorum-key-manager/src/store/keys"
	secrets "github.com/ConsenSysQuorum/quorum-key-manager/src/store/secrets"
	common "github.com/ethereum/go-ethereum/common"
	gomock "github.com/golang/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// GetAccountStore mocks base method.
func (m *MockManager) GetAccountStore(ctx context.Context, name string) (accounts.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountStore", ctx, name)
	ret0, _ := ret[0].(accounts.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountStore indicates an expected call of GetAccountStore.
func (mr *MockManagerMockRecorder) GetAccountStore(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountStore", reflect.TypeOf((*MockManager)(nil).GetAccountStore), ctx, name)
}

// GetAccountStoreByAddr mocks base method.
func (m *MockManager) GetAccountStoreByAddr(ctx context.Context, addr common.Address) (accounts.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountStoreByAddr", ctx, addr)
	ret0, _ := ret[0].(accounts.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountStoreByAddr indicates an expected call of GetAccountStoreByAddr.
func (mr *MockManagerMockRecorder) GetAccountStoreByAddr(ctx, addr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountStoreByAddr", reflect.TypeOf((*MockManager)(nil).GetAccountStoreByAddr), ctx, addr)
}

// GetKeyStore mocks base method.
func (m *MockManager) GetKeyStore(ctx context.Context, name string) (keys.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyStore", ctx, name)
	ret0, _ := ret[0].(keys.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyStore indicates an expected call of GetKeyStore.
func (mr *MockManagerMockRecorder) GetKeyStore(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyStore", reflect.TypeOf((*MockManager)(nil).GetKeyStore), ctx, name)
}

// GetSecretStore mocks base method.
func (m *MockManager) GetSecretStore(ctx context.Context, name string) (secrets.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretStore", ctx, name)
	ret0, _ := ret[0].(secrets.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretStore indicates an expected call of GetSecretStore.
func (mr *MockManagerMockRecorder) GetSecretStore(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretStore", reflect.TypeOf((*MockManager)(nil).GetSecretStore), ctx, name)
}

// List mocks base method.
func (m *MockManager) List(ctx context.Context, kind manifest.Kind) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, kind)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockManagerMockRecorder) List(ctx, kind interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockManager)(nil).List), ctx, kind)
}

// ListAllAccounts mocks base method.
func (m *MockManager) ListAllAccounts(arg0 context.Context) ([]*entities.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllAccounts", arg0)
	ret0, _ := ret[0].([]*entities.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllAccounts indicates an expected call of ListAllAccounts.
func (mr *MockManagerMockRecorder) ListAllAccounts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllAccounts", reflect.TypeOf((*MockManager)(nil).ListAllAccounts), arg0)
}

// Load mocks base method.
func (m *MockManager) Load(ctx context.Context, mnfsts ...*manifest.Manifest) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range mnfsts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Load", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockManagerMockRecorder) Load(ctx interface{}, mnfsts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, mnfsts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockManager)(nil).Load), varargs...)
}
