// Code generated by MockGen. DO NOT EDIT.
// Source: vault.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	api "github.com/hashicorp/vault/api"
	reflect "reflect"
)

// MockHashicorpVaultClient is a mock of HashicorpVaultClient interface
type MockHashicorpVaultClient struct {
	ctrl     *gomock.Controller
	recorder *MockHashicorpVaultClientMockRecorder
}

// MockHashicorpVaultClientMockRecorder is the mock recorder for MockHashicorpVaultClient
type MockHashicorpVaultClientMockRecorder struct {
	mock *MockHashicorpVaultClient
}

// NewMockHashicorpVaultClient creates a new mock instance
func NewMockHashicorpVaultClient(ctrl *gomock.Controller) *MockHashicorpVaultClient {
	mock := &MockHashicorpVaultClient{ctrl: ctrl}
	mock.recorder = &MockHashicorpVaultClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHashicorpVaultClient) EXPECT() *MockHashicorpVaultClientMockRecorder {
	return m.recorder
}

// Read mocks base method
func (m *MockHashicorpVaultClient) Read(path string) (*api.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", path)
	ret0, _ := ret[0].(*api.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read
func (mr *MockHashicorpVaultClientMockRecorder) Read(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockHashicorpVaultClient)(nil).Read), path)
}

// Write mocks base method
func (m *MockHashicorpVaultClient) Write(path string, data map[string]interface{}) (*api.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", path, data)
	ret0, _ := ret[0].(*api.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write
func (mr *MockHashicorpVaultClientMockRecorder) Write(path, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockHashicorpVaultClient)(nil).Write), path, data)
}

// List mocks base method
func (m *MockHashicorpVaultClient) List(path string) (*api.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", path)
	ret0, _ := ret[0].(*api.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockHashicorpVaultClientMockRecorder) List(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHashicorpVaultClient)(nil).List), path)
}
