// Code generated by MockGen. DO NOT EDIT.
// Source: authenticator.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	entities "github.com/consensys/quorum-key-manager/src/auth/entities"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockAuthenticator is a mock of Authenticator interface
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// AuthenticateJWT mocks base method
func (m *MockAuthenticator) AuthenticateJWT(ctx context.Context, token string) (*entities.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateJWT", ctx, token)
	ret0, _ := ret[0].(*entities.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateJWT indicates an expected call of AuthenticateJWT
func (mr *MockAuthenticatorMockRecorder) AuthenticateJWT(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateJWT", reflect.TypeOf((*MockAuthenticator)(nil).AuthenticateJWT), ctx, token)
}

// AuthenticateAPIKey mocks base method
func (m *MockAuthenticator) AuthenticateAPIKey(ctx context.Context, apiKey []byte) (*entities.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateAPIKey", ctx, apiKey)
	ret0, _ := ret[0].(*entities.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateAPIKey indicates an expected call of AuthenticateAPIKey
func (mr *MockAuthenticatorMockRecorder) AuthenticateAPIKey(ctx, apiKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateAPIKey", reflect.TypeOf((*MockAuthenticator)(nil).AuthenticateAPIKey), ctx, apiKey)
}
