kind: AKVKeys
version: 0.0.1
name: akv-keys
specs:
  vaultName: quorumkeymanager
  tenantID: 17255fb0-373b-4a1a-bd47-d211ab86df81
  clientID: 8c925036-dd6f-4a1e-a315-5e6fab4f2f09
  clientSecret: Cp1BSu50gx-._Q6UJQsSc2oQE-2b.cF.2y
---
kind: HashicorpSecrets
version: 0.0.1
name: hashicorp-secrets
  specs:
    mountPoint: secret
    address: http://localhost:8200
    token: '{VAULT_TOKEN}'
    namespace: ''
---
kind: Node
name: default
version: 0.0.0
  specs:
    rpc:
      addr: http://validator2:8545
      proxy:
        request:
            headers:
                Quorum-PSI:
                    - PSI1




                    kind: AKVSecrets
version: 0.0.1
name: akv-secrets
specs:
  vaultName: quorumkeymanager
  tenantID: 17255fb0-373b-4a1a-bd47-d211ab86df81
  clientID: 8c925036-dd6f-4a1e-a315-5e6fab4f2f09
  clientSecret: Cp1BSu50gx-._Q6UJQsSc2oQE-2b.cF.2y
---
kind: AKVKeys
version: 0.0.1
name: akv-keys
specs:
  vaultName: '{VAULT_NAME}'
  tenantID: '{TENANT_ID}'
  clientID: '{CLIENT_ID}'
  clientSecret: '{SECRET}'
---
kind: HashicorpSecrets
version: 0.0.1
name: hashicorp-secrets
specs:
  mountPoint: secret
  address: http://hashicorp:8200
  token: '{VAULT_TOKEN}'
  namespace: ''
---
kind: HashicorpKeys
version: 0.0.1
name: hashicorp-keys
specs:
  mountPoint: orchestrate
  address: http://hashicorp:8200
  tokenPath: '{VAULT_TOKEN_PATH}'
  namespace: ''
---
kind: Eth1Account
version: 0.0.1
name: eth1-accounts
specs:
  keystore: HashicorpKeys
  specs:
    mountPoint: secret
 address: http://hashicorp:8200
 token: '{VAULT_TOKEN}'
 namespace: ''
---
kind: Node
name: quorum-node
version: 0.0.0
specs:
  rpc:
    addr: http://quorum1:8545
  tessera:
    addr: http://tessera1:9080
---
kind: Node
name: besu-node
version: 0.0.0
specs:
  rpc:
    addr: http://validator1:8545
